title = "Player Data Manager"
changelog = true

[docusaurus]
tagline = "Easy player data management for Roblox"
onBrokenLinks = "ignore"
# url = "https://kyexyz.github.io"
baseUrl = '/'

[home]
enabled = true
includeReadme = true

[footer]
style = "dark"
